﻿var countries = [
  { name: "Aruba", code: "Aruba", country_code: "ABW" },
  { name: "Angola", code: "Angola", country_code: "AGO" },
  { name: "Anguilla", code: "Anguilla", country_code: "AIA" },
  { name: "Åland Islands", code: "Åland Islands", country_code: "ALA" },
  { name: "Albania", code: "Albania", country_code: "ALB" },
  { name: "Andorra", code: "Andorra", country_code: "AND" },
  { name: "Netherlands Antilles", code: "Netherlands Antilles", country_code: "ANT" },
  { name: "United Arab Emirates", code: "United Arab Emirates", country_code: "ARE" },
  { name: "Argentina", code: "Argentina", country_code: "ARG" },
  { name: "Armenia", code: "Armenia", country_code: "ARM" },
  { name: "American Samoa", code: "American Samoa", country_code: "ASM" },
  { name: "Antarctica", code: "Antarctica", country_code: "ATA" },
  { name: "French Southern Territories", code: "French Southern Territories", country_code: "ATF" },
  { name: "Antigua and Barbuda", code: "Antigua and Barbuda", country_code: "ATG" },
  { name: "Austria", code: "Austria", country_code: "AUT" },
  { name: "Azerbaijan", code: "Azerbaijan", country_code: "AZE" },
  { name: "Belgium", code: "Belgium", country_code: "BEL" },
  { name: "Benin", code: "Benin", country_code: "BEN" },
  { name: "Burkina Faso", code: "Burkina Faso", country_code: "BFA" },
  { name: "Bangladesh", code: "Bangladesh", country_code: "BGD" },
  { name: "Bulgaria", code: "Bulgaria", country_code: "BGR" },
  { name: "Bahrain", code: "Bahrain", country_code: "BHR" },
  { name: "Bahamas", code: "Bahamas", country_code: "BHS" },
  { name: "Bosnia and Herzegovina", code: "Bosnia and Herzegovina", country_code: "BIH" },
  { name: "Saint Barthélemy", code: "Saint Barthélemy", country_code: "BLM" },
  { name: "Belarus", code: "Belarus", country_code: "BLR" },
  { name: "Belize", code: "Belize", country_code: "BLZ" },
  { name: "Bermuda", code: "Bermuda", country_code: "BMU" },
  { name: "Bolivia", code: "Bolivia", country_code: "BOL" },
  { name: "Brazil", code: "Brazil", country_code: "BRA" },
  { name: "Barbados", code: "Barbados", country_code: "BRB" },
  { name: "Brunei Darussalam", code: "Brunei Darussalam", country_code: "BRN" },
  { name: "Bhutan", code: "Bhutan", country_code: "BTN" },
  { name: "Bouvet Island", code: "Bouvet Island", country_code: "BVT" },
  { name: "Botswana", code: "Botswana", country_code: "BWA" },
  { name: "Canada", code: "Canada", country_code: "CAN" },
  { name: "Cocos (Keeling) Islands", code: "Cocos (Keeling) Islands", country_code: "CCK" },
  { name: "Switzerland", code: "Switzerland", country_code: "CHE" },
  { name: "Chile", code: "Chile", country_code: "CHL" },
  { name: "China", code: "China", country_code: "CHN" },
  { name: "Côte d'Ivoire", code: "Côte d'Ivoire", country_code: "CIV" },
  { name: "Cameroon", code: "Cameroon", country_code: "CMR" },
  { name: "Democratic Republic of the Congo", code: "Democratic Republic of the Congo", country_code: "COD" },
  { name: "Congo", code: "Congo", country_code: "COG" },
  { name: "Cook Islands", code: "Cook Islands", country_code: "COK" },
  { name: "Colombia", code: "Colombia", country_code: "COL" },
  { name: "Comoros", code: "Comoros", country_code: "COM" },
  { name: "Cape Verde", code: "Cape Verde", country_code: "CPV" },
  { name: "Costa Rica", code: "Costa Rica", country_code: "CRI" },
  { name: "Cuba", code: "Cuba", country_code: "CUB" },
  { name: "Christmas Island", code: "Christmas Island", country_code: "CXR" },
  { name: "Cayman Islands", code: "Cayman Islands", country_code: "CYM" },
  { name: "Cyprus", code: "Cyprus", country_code: "CYP" },
  { name: "Czech Republic", code: "Czech Republic", country_code: "CZE" },
  { name: "Germany", code: "Germany", country_code: "DEU" },
  { name: "Djibouti", code: "Djibouti", country_code: "DJI" },
  { name: "Dominica", code: "Dominica", country_code: "DMA" },
  { name: "Denmark", code: "Denmark", country_code: "DNK" },
  { name: "Dominican Republic", code: "Dominican Republic", country_code: "DOM" },
  { name: "Algeria", code: "Algeria", country_code: "DZA" },
  { name: "Ecuador", code: "Ecuador", country_code: "ECU" },
  { name: "Egypt", code: "Egypt", country_code: "EGY" },
  { name: "Eritrea", code: "Eritrea", country_code: "ERI" },
  { name: "Western Sahara", code: "Western Sahara", country_code: "ESH" },
  { name: "Spain", code: "Spain", country_code: "ESP" },
  { name: "Estonia", code: "Estonia", country_code: "EST" },
  { name: "Ethiopia", code: "Ethiopia", country_code: "ETH" },
  { name: "Finland", code: "Finland", country_code: "FIN" },
  { name: "Fiji", code: "Fiji", country_code: "FJI" },
  { name: "Falkland Islands ", code: "Falkland Islands ", country_code: "FLK" },
  { name: "France", code: "France", country_code: "FRA" },
  { name: "Faroe Islands", code: "Faroe Islands", country_code: "FRO" },
  { name: "Micronesia", code: "Micronesia", country_code: "FSM" },
  { name: "Gabon", code: "Gabon", country_code: "GAB" },
  { name: "United Kingdom", code: "United Kingdom", country_code: "GBR" },
  { name: "Georgia", code: "Georgia", country_code: "GEO" },
  { name: "Guernsey", code: "Guernsey", country_code: "GGY" },
  { name: "Ghana", code: "Ghana", country_code: "GHA" },
  { name: "Gibraltar", code: "Gibraltar", country_code: "GIB" },
  { name: "Guinea", code: "Guinea", country_code: "GIN" },
  { name: "Guadeloupe", code: "Guadeloupe", country_code: "GLP" },
  { name: "Gambia", code: "Gambia", country_code: "GMB" },
  { name: "Guinea-Bissau", code: "Guinea-Bissau", country_code: "GNB" },
  { name: "Equatorial Guinea", code: "Equatorial Guinea", country_code: "GNQ" },
  { name: "Greece", code: "Greece", country_code: "GRC" },
  { name: "Grenada", code: "Grenada", country_code: "GRD" },
  { name: "Greenland", code: "Greenland", country_code: "GRL" },
  { name: "Guatemala", code: "Guatemala", country_code: "GTM" },
  { name: "French Guiana", code: "French Guiana", country_code: "GUF" },
  { name: "Guam", code: "Guam", country_code: "GUM" },
  { name: "Guyana", code: "Guyana", country_code: "GUY" },
  { name: "Hong Kong", code: "Hong Kong", country_code: "HKG" },
  { name: "Heard Island and McDonald Islands", code: "Heard Island and McDonald Islands", country_code: "HMD" },
  { name: "Honduras", code: "Honduras", country_code: "HND" },
  { name: "Croatia", code: "Croatia", country_code: "HRV" },
  { name: "Haiti", code: "Haiti", country_code: "HTI" },
  { name: "Hungary", code: "Hungary", country_code: "HUN" },
  { name: "Indonesia", code: "Indonesia", country_code: "IDN" },
  { name: "Isle of Man", code: "Isle of Man", country_code: "IMN" },
  { name: "India", code: "India", country_code: "IND" },
  { name: "British Indian Ocean Territory", code: "British Indian Ocean Territory", country_code: "IOT" },
  { name: "Ireland", code: "Ireland", country_code: "IRL" },
  { name: "Iceland", code: "Iceland", country_code: "ISL" },
  { name: "Israel", code: "Israel", country_code: "ISR" },
  { name: "Italy", code: "Italy", country_code: "ITA" },
  { name: "Jamaica", code: "Jamaica", country_code: "JAM" },
  { name: "Jersey", code: "Jersey", country_code: "JEY" },
  { name: "Jordan", code: "Jordan", country_code: "JOR" },
  { name: "Japan", code: "Japan", country_code: "JPN" },
  { name: "Kazakhstan", code: "Kazakhstan", country_code: "KAZ" },
  { name: "Kenya", code: "Kenya", country_code: "KEN" },
  { name: "Kyrgyzstan", code: "Kyrgyzstan", country_code: "KGZ" },
  { name: "Cambodia", code: "Cambodia", country_code: "KHM" },
  { name: "Kiribati", code: "Kiribati", country_code: "KIR" },
  { name: "Saint Kitts and Nevis", code: "Saint Kitts and Nevis", country_code: "KNA" },
  { name: "South Korea", code: "South Korea", country_code: "KOR" },
  { name: "Kuwait", code: "Kuwait", country_code: "KWT" },
  { name: "Laos", code: "Laos", country_code: "LAO" },
  { name: "Lebanon", code: "Lebanon", country_code: "LBN" },
  { name: "Liberia", code: "Liberia", country_code: "LBR" },
  { name: "Saint Lucia", code: "Saint Lucia", country_code: "LCA" },
  { name: "Liechtenstein", code: "Liechtenstein", country_code: "LIE" },
  { name: "Sri Lanka", code: "Sri Lanka", country_code: "LKA" },
  { name: "Lesotho", code: "Lesotho", country_code: "LSO" },
  { name: "Lithuania", code: "Lithuania", country_code: "LTU" },
  { name: "Luxembourg", code: "Luxembourg", country_code: "LUX" },
  { name: "Latvia", code: "Latvia", country_code: "LVA" },
  { name: "Macao", code: "Macao", country_code: "MAC" },
  { name: "Saint Martin (French part)", code: "Saint Martin (French part)", country_code: "MAF" },
  { name: "Morocco", code: "Morocco", country_code: "MAR" },
  { name: "Monaco", code: "Monaco", country_code: "MCO" },
  { name: "Moldova", code: "Moldova", country_code: "MDA" },
  { name: "Madagascar", code: "Madagascar", country_code: "MDG" },
  { name: "Maldives", code: "Maldives", country_code: "MDV" },
  { name: "Mexico", code: "Mexico", country_code: "MEX" },
  { name: "Marshall Islands", code: "Marshall Islands", country_code: "MHL" },
  { name: "Macedonia", code: "Macedonia", country_code: "MKD" },
  { name: "Malta", code: "Malta", country_code: "MLT" },
  { name: "Myanmar", code: "Myanmar", country_code: "MMR" },
  { name: "Montenegro", code: "Montenegro", country_code: "MNE" },
  { name: "Mongolia", code: "Mongolia", country_code: "MNG" },
  { name: "Northern Mariana Islands", code: "Northern Mariana Islands", country_code: "MNP" },
  { name: "Mozambique", code: "Mozambique", country_code: "MOZ" },
  { name: "Mauritania", code: "Mauritania", country_code: "MRT" },
  { name: "Montserrat", code: "Montserrat", country_code: "MSR" },
  { name: "Martinique", code: "Martinique", country_code: "MTQ" },
  { name: "Mauritius", code: "Mauritius", country_code: "MUS" },
  { name: "Malawi", code: "Malawi", country_code: "MWI" },
  { name: "Malaysia", code: "Malaysia", country_code: "MYS" },
  { name: "Mayotte", code: "Mayotte", country_code: "MYT" },
  { name: "Namibia", code: "Namibia", country_code: "NAM" },
  { name: "New Caledonia", code: "New Caledonia", country_code: "NCL" },
  { name: "Norfolk Island", code: "Norfolk Island", country_code: "NFK" },
  { name: "Nigeria", code: "Nigeria", country_code: "NGA" },
  { name: "Nicaragua", code: "Nicaragua", country_code: "NIC" },
  { name: "Niue", code: "Niue", country_code: "NIU" },
  { name: "Netherlands", code: "Netherlands", country_code: "NLD" },
  { name: "Norway", code: "Norway", country_code: "NOR" },
  { name: "Nepal", code: "Nepal", country_code: "NPL" },
  { name: "Nauru", code: "Nauru", country_code: "NRU" },
  { name: "New Zealand", code: "New Zealand", country_code: "NZL" },
  { name: "Oman", code: "Oman", country_code: "OMN" },
  { name: "Pakistan", code: "Pakistan", country_code: "PAK" },
  { name: "Panama", code: "Panama", country_code: "PAN" },
  { name: "Pitcairn", code: "Pitcairn", country_code: "PCN" },
  { name: "Peru", code: "Peru", country_code: "PER" },
  { name: "Philippines", code: "Philippines", country_code: "PHL" },
  { name: "Palau", code: "Palau", country_code: "PLW" },
  { name: "Papua New Guinea", code: "Papua New Guinea", country_code: "PNG" },
  { name: "Poland", code: "Poland", country_code: "POL" },
  { name: "Puerto Rico", code: "Puerto Rico", country_code: "PRI" },
  { name: "Portugal", code: "Portugal", country_code: "PRT" },
  { name: "Paraguay", code: "Paraguay", country_code: "PRY" },
  { name: "Palestinian Territory, Occupied", code: "Palestinian Territory, Occupied", country_code: "PSE" },
  { name: "French Polynesia", code: "French Polynesia", country_code: "PYF" },
  { name: "Qatar", code: "Qatar", country_code: "QAT" },
  { name: "Réunion", code: "Réunion", country_code: "REU" },
  { name: "Romania", code: "Romania", country_code: "ROU" },
  { name: "Russia", code: "Russia", country_code: "RUS" },
  { name: "Rwanda", code: "Rwanda", country_code: "RWA" },
  { name: "Saudi Arabia", code: "Saudi Arabia", country_code: "SAU" },
  { name: "Senegal", code: "Senegal", country_code: "SEN" },
  { name: "Singapore", code: "Singapore", country_code: "SGP" },
  { name: "South Georgia and the South Sandwich Islands", code: "South Georgia and the South Sandwich Islands", country_code: "SGS" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "Saint Helena, Ascension and Tristan da Cunha", country_code: "SHN" },
  { name: "Svalbard and Jan Mayen", code: "Svalbard and Jan Mayen", country_code: "SJM" },
  { name: "Solomon Islands", code: "Solomon Islands", country_code: "SLB" },
  { name: "Sierra Leone", code: "Sierra Leone", country_code: "SLE" },
  { name: "El Salvador", code: "El Salvador", country_code: "SLV" },
  { name: "San Marino", code: "San Marino", country_code: "SMR" },
  { name: "Saint Pierre and Miquelon", code: "Saint Pierre and Miquelon", country_code: "SPM" },
  { name: "Serbia", code: "Serbia", country_code: "SRB" },
  { name: "Sao Tome and Principe", code: "Sao Tome and Principe", country_code: "STP" },
  { name: "Suriname", code: "Suriname", country_code: "SUR" },
  { name: "Slovakia", code: "Slovakia", country_code: "SVK" },
  { name: "Slovenia", code: "Slovenia", country_code: "SVN" },
  { name: "Sweden", code: "Sweden", country_code: "SWE" },
  { name: "Swaziland", code: "Swaziland", country_code: "SWZ" },
  { name: "Seychelles", code: "Seychelles", country_code: "SYC" },
  { name: "Turks and Caicos Islands", code: "Turks and Caicos Islands", country_code: "TCA" },
  { name: "Togo", code: "Togo", country_code: "TGO" },
  { name: "Thailand", code: "Thailand", country_code: "THA" },
  { name: "Tajikistan", code: "Tajikistan", country_code: "TJK" },
  { name: "Tokelau", code: "Tokelau", country_code: "TKL" },
  { name: "Turkmenistan", code: "Turkmenistan", country_code: "TKM" },
  { name: "Timor-Leste", code: "Timor-Leste", country_code: "TLS" },
  { name: "Tonga", code: "Tonga", country_code: "TON" },
  { name: "Trinidad and Tobago", code: "Trinidad and Tobago", country_code: "TTO" },
  { name: "Tunisia", code: "Tunisia", country_code: "TUN" },
  { name: "Turkey", code: "Turkey", country_code: "TUR" },
  { name: "Tuvalu", code: "Tuvalu", country_code: "TUV" },
  { name: "Taiwan", code: "Taiwan", country_code: "TWN" },
  { name: "Tanzania", code: "Tanzania", country_code: "TZA" },
  { name: "Uganda", code: "Uganda", country_code: "UGA" },
  { name: "United States Minor Outlying Islands", code: "United States Minor Outlying Islands", country_code: "UMI" },
  { name: "Uruguay", code: "Uruguay", country_code: "URY" },
  { name: "United States", code: "United States", country_code: "USA" },
  { name: "Uzbekistan", code: "Uzbekistan", country_code: "UZB" },
  { name: "Holy See (Vatican City State)", code: "Holy See (Vatican City State)", country_code: "VAT" },
  { name: "Saint Vincent and the Grenadines", code: "Saint Vincent and the Grenadines", country_code: "VCT" },
  { name: "Virgin Islands, British", code: "Virgin Islands, British", country_code: "VGB" },
  { name: "Virgin Islands, U.S.", code: "Virgin Islands, U.S.", country_code: "VIR" },
  { name: "Viet Nam", code: "Viet Nam", country_code: "VNM" },
  { name: "Vietnam", code: "Viet Nam", country_code: "VNM" },
  { name: "Vanuatu", code: "Vanuatu", country_code: "VUT" },
  { name: "Wallis and Futuna", code: "Wallis and Futuna", country_code: "WLF" },
  { name: "Samoa", code: "Samoa", country_code: "WSM" },
  { name: "South Africa", code: "South Africa", country_code: "ZAF" },
  { name: "Zambia", code: "Zambia", country_code: "ZMB" },
  { name: "Zimbabwe", code: "Zimbabwe", country_code: "ZWE" },
  { name: "Bali", code: "Bali", country_code: "BAL" },
  { name: "Tahiti", code: "Tahiti", country_code: "TAH" },
  { name: "Antarctic Flyover", code: "Antarctic Flyover", country_code: "ANF" },
  { name: "Caroline Islands", code: "Caroline Islands", country_code: "CAI" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "Bonaire, Sint Eustatius and Saba", country_code: "BES" },
  { name: "Curacao", code: "Curacao", country_code: "CUW" },
  { name: "Sint Maarten", code: "Sint Maarten", country_code: "SXM" },
  { name: "Arctic Circle", code: "Arctic Circle", country_code: "ARC" },
  { name: "Caribbean Islands", code: "Caribbean Islands", country_code: "CBI" },
  { name: "Hawaiian Islands", code: "Hawaiian Islands", country_code: "HI" },
  { name: "Kosovo", code: "Kosovo", country_code: "XKX" }
]

const getNames = () => countries.map(c => c.name)

const getCodeByName = name => {
  const country = countries.find(c => c.name === name)
  return country ? country.code : undefined;
}

module.exports = {
  countries,
  getNames,
  getCodeByName
}
